import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import '../../core/network/api_client.dart';
import '../../core/session/session_manager.dart';

class ComplaintFormScreen extends StatefulWidget {
  const ComplaintFormScreen({super.key});

  @override
  State<ComplaintFormScreen> createState() => _ComplaintFormScreenState();
}

class _ComplaintFormScreenState extends State<ComplaintFormScreen> {
  final _formKey = GlobalKey<FormState>();
  final _titleController = TextEditingController();
  final _descController = TextEditingController();
  final _locationController = TextEditingController();
  String _priority = 'Medium';
  String _entityType = 'Room';
  bool _isSubmitting = false;

  final _priorities = ['Low', 'Medium', 'High', 'Critical'];
  final _entityTypes = ['Room', 'Floor', 'Building', 'Asset'];

  Color _priorityColor(String p) {
    switch (p) {
      case 'Critical': return const Color(0xFF9B2020);
      case 'High':     return const Color(0xFFA05A10);
      case 'Medium':   return const Color(0xFF1E5080);
      case 'Low':      return const Color(0xFF2D6B4F);
      default:         return const Color(0xFF8C8278);
    }
  }

  @override
  void dispose() {
    _titleController.dispose();
    _descController.dispose();
    _locationController.dispose();
    super.dispose();
  }

  Future<void> _submit() async {
    if (!_formKey.currentState!.validate()) return;
    setState(() => _isSubmitting = true);
    try {
      final session = SessionManager();
      await ApiClient.post('/Complaints', {
        'title': _titleController.text.trim(),
        'description': _descController.text.trim(),
        'entityName': _locationController.text.trim(),
        'entityType': _entityType,
        'entityId': '',
        'buildingId': session.selectedBuildingId ?? '',
        'priority': _priority,
        'status': 'Open',
        'isAutoGenerated': false,
        'reportedByName': session.currentUser?['name'] ?? 'Field Worker',
        'reportedById': session.currentUser?['id'] ?? '',
      });

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Row(children: [
              Icon(Icons.check_circle, color: Colors.white),
              SizedBox(width: 8),
              Text('Complaint submitted successfully'),
            ]),
            backgroundColor: Color(0xFF2D6B4F),
          ),
        );
        context.pop(true);
      }
    } catch (_) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Failed to submit. Please try again.'), backgroundColor: Color(0xFF9B2020)),
        );
      }
    }
    setState(() => _isSubmitting = false);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFFF7F3EC),
      appBar: AppBar(
        backgroundColor: Colors.white,
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.close_rounded, color: Color(0xFF1A1714)),
          onPressed: () => context.pop(),
        ),
        title: const Text('Report Issue', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 18, color: Color(0xFF1A1714))),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.fromLTRB(18, 18, 18, 100),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              _sectionLabel('Issue Details'),
              const SizedBox(height: 12),

              _fieldLabel('Title *'),
              TextFormField(
                controller: _titleController,
                style: const TextStyle(color: Color(0xFF1A1714), fontSize: 15),
                decoration: _inputDecoration('e.g. Water leakage in washroom'),
                validator: (v) => v == null || v.trim().isEmpty ? 'Required' : null,
              ),
              const SizedBox(height: 16),

              _fieldLabel('Description'),
              TextFormField(
                controller: _descController,
                maxLines: 3,
                style: const TextStyle(color: Color(0xFF1A1714), fontSize: 15),
                decoration: _inputDecoration('Describe the issue in detail...'),
              ),
              const SizedBox(height: 24),

              _sectionLabel('Priority'),
              const SizedBox(height: 12),
              Row(children: _priorities.map((p) {
                final isSelected = _priority == p;
                final color = _priorityColor(p);
                return Expanded(
                  child: Padding(
                    padding: EdgeInsets.only(right: p != _priorities.last ? 8 : 0),
                    child: GestureDetector(
                      onTap: () => setState(() => _priority = p),
                      child: AnimatedContainer(
                        duration: const Duration(milliseconds: 150),
                        height: 48,
                        decoration: BoxDecoration(
                          color: isSelected ? color.withValues(alpha: 0.1) : Colors.white,
                          borderRadius: BorderRadius.circular(12),
                          border: Border.all(color: isSelected ? color : const Color(0xFFDDD5C8), width: isSelected ? 2 : 1),
                        ),
                        child: Center(
                          child: Text(
                            p,
                            style: TextStyle(
                              fontSize: 13,
                              fontWeight: FontWeight.bold,
                              color: isSelected ? color : const Color(0xFF8C8278),
                            ),
                          ),
                        ),
                      ),
                    ),
                  ),
                );
              }).toList()),

              const SizedBox(height: 24),
              _sectionLabel('Location'),
              const SizedBox(height: 12),

              _fieldLabel('Location Name *'),
              TextFormField(
                controller: _locationController,
                style: const TextStyle(color: Color(0xFF1A1714), fontSize: 15),
                decoration: _inputDecoration('e.g. Washroom A, Level 2'),
                validator: (v) => v == null || v.trim().isEmpty ? 'Required' : null,
              ),
              const SizedBox(height: 16),

              _fieldLabel('Location Type'),
              DropdownButtonFormField<String>(
                value: _entityType,
                style: const TextStyle(color: Color(0xFF1A1714), fontSize: 15),
                decoration: _inputDecoration(''),
                dropdownColor: Colors.white,
                items: _entityTypes.map((t) => DropdownMenuItem(value: t, child: Text(t))).toList(),
                onChanged: (v) => setState(() => _entityType = v!),
              ),

              const SizedBox(height: 32),

              GestureDetector(
                onTap: _isSubmitting ? null : _submit,
                child: Container(
                  width: double.infinity,
                  height: 56,
                  decoration: BoxDecoration(
                    color: _isSubmitting ? const Color(0xFF8C8278) : const Color(0xFF9B2020),
                    borderRadius: BorderRadius.circular(16),
                    boxShadow: _isSubmitting ? [] : [BoxShadow(color: const Color(0xFF9B2020).withValues(alpha: 0.3), blurRadius: 16, offset: const Offset(0, 6))],
                  ),
                  child: Center(
                    child: _isSubmitting
                        ? const SizedBox(width: 22, height: 22, child: CircularProgressIndicator(strokeWidth: 2, color: Colors.white))
                        : const Row(
                            mainAxisAlignment: MainAxisAlignment.center,
                            children: [
                              Icon(Icons.report_problem_rounded, color: Colors.white, size: 20),
                              SizedBox(width: 10),
                              Text('Submit Report', style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold, color: Colors.white)),
                            ],
                          ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _sectionLabel(String text) => Text(
    text,
    style: const TextStyle(fontSize: 12, fontWeight: FontWeight.w700, color: Color(0xFF8C8278), letterSpacing: 0.8),
  );

  Widget _fieldLabel(String text) => Padding(
    padding: const EdgeInsets.only(bottom: 8),
    child: Text(text, style: const TextStyle(fontSize: 14, fontWeight: FontWeight.w600, color: Color(0xFF4A4540))),
  );

  InputDecoration _inputDecoration(String hint) => InputDecoration(
    hintText: hint,
    hintStyle: const TextStyle(color: Color(0xFFBBB3A8), fontSize: 14),
    filled: true,
    fillColor: const Color(0xFFEEE8DF),
    border: OutlineInputBorder(borderRadius: BorderRadius.circular(14), borderSide: BorderSide.none),
    enabledBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(14), borderSide: BorderSide.none),
    focusedBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(14), borderSide: const BorderSide(color: Color(0xFF1E3D2F), width: 1.5)),
    errorBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(14), borderSide: const BorderSide(color: Color(0xFF9B2020))),
    focusedErrorBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(14), borderSide: const BorderSide(color: Color(0xFF9B2020), width: 1.5)),
    contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 16),
  );
}
