import { useEffect, useState } from 'react'
import { AlertCircle, Search, Clock, MapPin, X, User, ChevronDown } from 'lucide-react'
import api from '../api/client'

const PRIORITY_STYLE = {
  Critical: 'bg-red-100 text-red-700',
  High:     'bg-orange-50 text-orange-700',
  Medium:   'bg-blue-50 text-blue-700',
  Low:      'bg-green-50 text-green-700',
}
const STATUS_STYLE = {
  Open:          'bg-red-50 text-red-700',
  'In Progress': 'bg-blue-50 text-blue-700',
  Resolved:      'bg-green-50 text-green-700',
  Closed:        'bg-gray-100 text-gray-600',
}
const STATUSES = ['Open', 'In Progress', 'Resolved', 'Closed']

function DetailDrawer({ complaint, users, onClose, onUpdate }) {
  const [status, setStatus] = useState(complaint.status)
  const [assignee, setAssignee] = useState(complaint.assignedToName || '')
  const [saving, setSaving] = useState(false)

  async function save() {
    setSaving(true)
    try {
      if (assignee && assignee !== complaint.assignedToName) {
        await api.put(`/Complaints/${complaint.id}/assign`, { assignedToName: assignee })
      }
      if (status !== complaint.status) {
        await api.put(`/Complaints/${complaint.id}/status`, { status })
      }
      onUpdate()
      onClose()
    } catch (_) {}
    setSaving(false)
  }

  return (
    <div className="fixed inset-0 bg-black/40 flex justify-end z-50" onClick={onClose}>
      <div className="bg-white w-full max-w-md h-full shadow-2xl flex flex-col overflow-y-auto" onClick={e => e.stopPropagation()}>
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-gray-100">
          <h2 className="font-bold text-gray-900">Complaint Detail</h2>
          <button onClick={onClose} className="p-1.5 hover:bg-gray-100 rounded-lg"><X size={16} /></button>
        </div>

        <div className="flex-1 p-6 space-y-5">
          {/* Title + priority */}
          <div>
            <div className="flex items-start gap-2">
              <span className={`badge mt-0.5 ${PRIORITY_STYLE[complaint.priority] || 'bg-gray-100 text-gray-600'}`}>{complaint.priority}</span>
              <h3 className="font-bold text-gray-900 text-base leading-snug">{complaint.title}</h3>
            </div>
            {complaint.description && <p className="text-sm text-gray-500 mt-2">{complaint.description}</p>}
          </div>

          {/* Meta */}
          <div className="space-y-2">
            <div className="flex items-center gap-2 text-sm text-gray-500">
              <MapPin size={14} className="text-gray-400 flex-shrink-0" />
              <span>{complaint.entityName} ({complaint.entityType})</span>
            </div>
            <div className="flex items-center gap-2 text-sm text-gray-500">
              <Clock size={14} className="text-gray-400 flex-shrink-0" />
              <span>{new Date(complaint.createdAt).toLocaleString()}</span>
            </div>
            {complaint.reportedByName && (
              <div className="flex items-center gap-2 text-sm text-gray-500">
                <User size={14} className="text-gray-400 flex-shrink-0" />
                <span>Reported by {complaint.reportedByName}</span>
              </div>
            )}
          </div>

          <hr className="border-gray-100" />

          {/* Status */}
          <div>
            <label className="text-xs font-semibold text-gray-500 uppercase tracking-wide block mb-2">Status</label>
            <div className="grid grid-cols-2 gap-2">
              {STATUSES.map(s => (
                <button key={s} onClick={() => setStatus(s)}
                  className={`px-3 py-2 rounded-lg text-sm font-semibold border transition-all ${status === s ? `${STATUS_STYLE[s]} border-current` : 'border-gray-200 text-gray-500 hover:bg-gray-50'}`}>
                  {s}
                </button>
              ))}
            </div>
          </div>

          {/* Assign to */}
          <div>
            <label className="text-xs font-semibold text-gray-500 uppercase tracking-wide block mb-2">Assign To</label>
            <div className="relative">
              <select
                className="input appearance-none pr-8"
                value={assignee}
                onChange={e => setAssignee(e.target.value)}
              >
                <option value="">Unassigned</option>
                {users.filter(u => u.role === 'Technician' || u.role === 'Supervisor').map(u => (
                  <option key={u.id} value={u.name}>{u.name} ({u.role})</option>
                ))}
              </select>
              <ChevronDown size={14} className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 pointer-events-none" />
            </div>
          </div>

          {complaint.isAutoGenerated && (
            <div className="bg-gray-50 rounded-lg p-3 text-xs text-gray-500">
              Auto-generated from a failed checklist task
            </div>
          )}
        </div>

        <div className="p-6 border-t border-gray-100">
          <div className="flex gap-3">
            <button onClick={onClose} className="btn-secondary flex-1">Cancel</button>
            <button onClick={save} disabled={saving} className="btn-primary flex-1">
              {saving ? 'Saving...' : 'Save Changes'}
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}

export default function Complaints() {
  const [complaints, setComplaints] = useState([])
  const [users, setUsers] = useState([])
  const [loading, setLoading] = useState(true)
  const [search, setSearch] = useState('')
  const [statusFilter, setStatusFilter] = useState('All')
  const [selected, setSelected] = useState(null)

  useEffect(() => { fetchAll() }, [])

  async function fetchAll() {
    try {
      const [cr, ur] = await Promise.all([api.get('/Complaints'), api.get('/Users')])
      setComplaints(cr.data)
      setUsers(ur.data)
    } catch (_) {}
    setLoading(false)
  }

  const statuses = ['All', ...STATUSES]
  const filtered = complaints
    .filter(c => statusFilter === 'All' || c.status === statusFilter)
    .filter(c => c.title?.toLowerCase().includes(search.toLowerCase()) || c.entityName?.toLowerCase().includes(search.toLowerCase()))

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Complaints</h1>
          <p className="text-sm text-gray-500 mt-1">{complaints.filter(c => c.status === 'Open').length} open issues</p>
        </div>
      </div>

      <div className="flex items-center gap-2 flex-wrap">
        {statuses.map(s => (
          <button key={s} onClick={() => setStatusFilter(s)}
            className={`px-4 py-1.5 rounded-full text-sm font-semibold transition-colors ${statusFilter === s ? 'bg-brand-600 text-white' : 'bg-white border border-gray-200 text-gray-500 hover:bg-gray-50'}`}>
            {s}
          </button>
        ))}
        <div className="ml-auto flex items-center gap-2 bg-white border border-gray-200 rounded-lg px-3 py-1.5">
          <Search size={14} className="text-gray-400" />
          <input placeholder="Search..." value={search} onChange={e => setSearch(e.target.value)} className="bg-transparent text-sm outline-none placeholder-gray-400 w-40" />
        </div>
      </div>

      {loading ? (
        <div className="text-center text-gray-400 py-16 text-sm">Loading...</div>
      ) : filtered.length === 0 ? (
        <div className="card p-16 text-center">
          <AlertCircle size={40} className="text-gray-300 mx-auto mb-3" />
          <p className="text-sm text-gray-500">No complaints found</p>
        </div>
      ) : (
        <div className="card overflow-hidden">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-gray-100 bg-gray-50">
                {['Issue', 'Priority', 'Location', 'Status', 'Assigned', 'Reported', 'Source'].map(h => (
                  <th key={h} className="text-left px-5 py-3 text-xs font-bold text-gray-500 uppercase tracking-wide">{h}</th>
                ))}
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-50">
              {filtered.map(c => (
                <tr key={c.id} onClick={() => setSelected(c)} className="hover:bg-gray-50 cursor-pointer">
                  <td className="px-5 py-3.5">
                    <p className="font-semibold text-gray-800">{c.title}</p>
                    {c.description && <p className="text-xs text-gray-400 truncate max-w-xs">{c.description}</p>}
                  </td>
                  <td className="px-5 py-3.5">
                    <span className={`badge ${PRIORITY_STYLE[c.priority] || 'bg-gray-100 text-gray-600'}`}>{c.priority}</span>
                  </td>
                  <td className="px-5 py-3.5">
                    <span className="flex items-center gap-1.5 text-xs text-gray-500">
                      <MapPin size={12} /> {c.entityName}
                    </span>
                  </td>
                  <td className="px-5 py-3.5">
                    <span className={`badge ${STATUS_STYLE[c.status] || 'bg-gray-100 text-gray-600'}`}>{c.status}</span>
                  </td>
                  <td className="px-5 py-3.5">
                    <span className="text-xs text-gray-500">{c.assignedToName || <span className="text-gray-300 italic">Unassigned</span>}</span>
                  </td>
                  <td className="px-5 py-3.5">
                    <span className="flex items-center gap-1.5 text-xs text-gray-400">
                      <Clock size={12} /> {new Date(c.createdAt).toLocaleDateString()}
                    </span>
                  </td>
                  <td className="px-5 py-3.5">
                    {c.isAutoGenerated
                      ? <span className="badge bg-gray-100 text-gray-500">Auto</span>
                      : <span className="badge bg-blue-50 text-blue-600">Manual</span>}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {selected && (
        <DetailDrawer
          complaint={selected}
          users={users}
          onClose={() => setSelected(null)}
          onUpdate={fetchAll}
        />
      )}
    </div>
  )
}
