// <auto-generated />
using System;
using FacilityPro.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FacilityPro.Infrastructure.Migrations
{
    [DbContext(typeof(FacilityDbContext))]
    [Migration("20260627211834_AddSpatialMappingFields")]
    partial class AddSpatialMappingFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("FacilityPro.Domain.Entities.Asset", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double?>("AssetPosX")
                        .HasColumnType("REAL");

                    b.Property<double?>("AssetPosY")
                        .HasColumnType("REAL");

                    b.Property<string>("BuildingId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FloorId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InstallDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QrCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RoomId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("FloorId");

                    b.HasIndex("RoomId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("FacilityPro.Domain.Entities.AssetCategory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentCategoryId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("AssetCategories");
                });

            modelBuilder.Entity("FacilityPro.Domain.Entities.AssetCategoryField", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("AssetCategoryFields");
                });

            modelBuilder.Entity("FacilityPro.Domain.Entities.AssetFieldValue", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("FieldId");

                    b.ToTable("AssetFieldValues");
                });

            modelBuilder.Entity("FacilityPro.Domain.Entities.Building", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LobbyQrCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("TargetLat")
                        .HasColumnType("REAL");

                    b.Property<double?>("TargetLng")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("FacilityPro.Domain.Entities.ChecklistAssignment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChecklistTemplateId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistTemplateId");

                    b.ToTable("ChecklistAssignments");
                });

            modelBuilder.Entity("FacilityPro.Domain.Entities.ChecklistMapping", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChecklistId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChecklistName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FloorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoomId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("FloorId");

                    b.HasIndex("RoomId");

                    b.ToTable("ChecklistMappings");
                });

            modelBuilder.Entity("FacilityPro.Domain.Entities.ChecklistTemplate", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BuildingId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ChecklistTemplates");
                });

            modelBuilder.Entity("FacilityPro.Domain.Entities.Client", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("FacilityPro.Domain.Entities.Complaint", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedToName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BuildingId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAutoGenerated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportedByName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceTaskId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Complaints");
                });

            modelBuilder.Entity("FacilityPro.Domain.Entities.Floor", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BuildingId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("CanvasHeight")
                        .HasColumnType("REAL");

                    b.Property<double>("CanvasWidth")
                        .HasColumnType("REAL");

                    b.Property<int>("FloorNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FloorPlanImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QrCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("Floors");
                });

            modelBuilder.Entity("FacilityPro.Domain.Entities.PmSchedule", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedToName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BuildingId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChecklistTemplateId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DayOfMonth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HourOfDay")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastGeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PmSchedules");
                });

            modelBuilder.Entity("FacilityPro.Domain.Entities.Room", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FloorId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Height")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("PosX")
                        .HasColumnType("REAL");

                    b.Property<double>("PosY")
                        .HasColumnType("REAL");

                    b.Property<string>("QrCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Width")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("FloorId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("FacilityPro.Domain.Entities.TaskAppEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AwaySeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageName")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskAppEvents");
                });

            modelBuilder.Entity("FacilityPro.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FacilityPro.Domain.Entities.UserBuildingMapping", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BuildingId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("UserId");

                    b.ToTable("UserBuildingMappings");
                });

            modelBuilder.Entity("FacilityPro.Domain.Entities.WorkerSession", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double?>("ArrivalLat")
                        .HasColumnType("REAL");

                    b.Property<double?>("ArrivalLng")
                        .HasColumnType("REAL");

                    b.Property<string>("BuildingId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("DistanceFromBuilding")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastAssetId")
                        .HasColumnType("TEXT");

                    b.Property<int>("LastFloorNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastScanAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("WorkerId");

                    b.ToTable("WorkerSessions");
                });

            modelBuilder.Entity("FacilityPro.Domain.Entities.WorkerTask", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedToId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedToName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BuildingId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QrCodeScanned")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ScheduledTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("FacilityPro.Domain.Entities.Asset", b =>
                {
                    b.HasOne("FacilityPro.Domain.Entities.Building", "Building")
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FacilityPro.Domain.Entities.AssetCategory", "Category")
                        .WithMany("Assets")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FacilityPro.Domain.Entities.Floor", "Floor")
                        .WithMany()
                        .HasForeignKey("FloorId");

                    b.HasOne("FacilityPro.Domain.Entities.Room", "Room")
                        .WithMany("Assets")
                        .HasForeignKey("RoomId");

                    b.Navigation("Building");

                    b.Navigation("Category");

                    b.Navigation("Floor");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("FacilityPro.Domain.Entities.AssetCategory", b =>
                {
                    b.HasOne("FacilityPro.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FacilityPro.Domain.Entities.AssetCategory", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Client");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("FacilityPro.Domain.Entities.AssetCategoryField", b =>
                {
                    b.HasOne("FacilityPro.Domain.Entities.AssetCategory", "Category")
                        .WithMany("Fields")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FacilityPro.Domain.Entities.AssetFieldValue", b =>
                {
                    b.HasOne("FacilityPro.Domain.Entities.Asset", "Asset")
                        .WithMany("FieldValues")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FacilityPro.Domain.Entities.AssetCategoryField", "Field")
                        .WithMany()
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Field");
                });

            modelBuilder.Entity("FacilityPro.Domain.Entities.Building", b =>
                {
                    b.HasOne("FacilityPro.Domain.Entities.Client", "Client")
                        .WithMany("Buildings")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("FacilityPro.Domain.Entities.ChecklistAssignment", b =>
                {
                    b.HasOne("FacilityPro.Domain.Entities.ChecklistTemplate", "Template")
                        .WithMany("Assignments")
                        .HasForeignKey("ChecklistTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("FacilityPro.Domain.Entities.ChecklistMapping", b =>
                {
                    b.HasOne("FacilityPro.Domain.Entities.Asset", "Asset")
                        .WithMany("ChecklistMappings")
                        .HasForeignKey("AssetId");

                    b.HasOne("FacilityPro.Domain.Entities.Floor", "Floor")
                        .WithMany("ChecklistMappings")
                        .HasForeignKey("FloorId");

                    b.HasOne("FacilityPro.Domain.Entities.Room", "Room")
                        .WithMany("ChecklistMappings")
                        .HasForeignKey("RoomId");

                    b.Navigation("Asset");

                    b.Navigation("Floor");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("FacilityPro.Domain.Entities.Floor", b =>
                {
                    b.HasOne("FacilityPro.Domain.Entities.Building", "Building")
                        .WithMany("Floors")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("FacilityPro.Domain.Entities.Room", b =>
                {
                    b.HasOne("FacilityPro.Domain.Entities.Floor", "Floor")
                        .WithMany("Rooms")
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Floor");
                });

            modelBuilder.Entity("FacilityPro.Domain.Entities.TaskAppEvent", b =>
                {
                    b.HasOne("FacilityPro.Domain.Entities.WorkerTask", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("FacilityPro.Domain.Entities.UserBuildingMapping", b =>
                {
                    b.HasOne("FacilityPro.Domain.Entities.Building", "Building")
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FacilityPro.Domain.Entities.User", "User")
                        .WithMany("BuildingMappings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FacilityPro.Domain.Entities.WorkerSession", b =>
                {
                    b.HasOne("FacilityPro.Domain.Entities.Building", "Building")
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FacilityPro.Domain.Entities.User", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Building");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("FacilityPro.Domain.Entities.Asset", b =>
                {
                    b.Navigation("ChecklistMappings");

                    b.Navigation("FieldValues");
                });

            modelBuilder.Entity("FacilityPro.Domain.Entities.AssetCategory", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Fields");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("FacilityPro.Domain.Entities.Building", b =>
                {
                    b.Navigation("Floors");
                });

            modelBuilder.Entity("FacilityPro.Domain.Entities.ChecklistTemplate", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("FacilityPro.Domain.Entities.Client", b =>
                {
                    b.Navigation("Buildings");
                });

            modelBuilder.Entity("FacilityPro.Domain.Entities.Floor", b =>
                {
                    b.Navigation("ChecklistMappings");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("FacilityPro.Domain.Entities.Room", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("ChecklistMappings");
                });

            modelBuilder.Entity("FacilityPro.Domain.Entities.User", b =>
                {
                    b.Navigation("BuildingMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
