namespace FacilityPro.Domain.Entities;

public class Complaint
{
    public string Id { get; set; } = Guid.NewGuid().ToString();
    public string Title { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;
    
    // Location Mapping
    public string EntityId { get; set; } = string.Empty;
    public string EntityType { get; set; } = string.Empty; // "Building", "Floor", "Room", "Asset"
    public string EntityName { get; set; } = string.Empty; // Denormalized location name
    public string BuildingId { get; set; } = string.Empty;
    
    // Auto-generation tracking
    public bool IsAutoGenerated { get; set; } = false;
    public string? SourceTaskId { get; set; } // If failed from a checklist
    
    public string Priority { get; set; } = "Medium"; // Critical, High, Medium, Low
    public string Status { get; set; } = "Open"; // Open, In Progress, Resolved, Closed
    public string AssignedToName { get; set; } = string.Empty;
    public string ReportedByName { get; set; } = string.Empty;
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime? ResolvedAt { get; set; }
    public string? ReportedById { get; set; }
}
