using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using FacilityPro.Infrastructure.Data;
using FacilityPro.Domain.Entities;

namespace FacilityPro.Api.Controllers;

public record UpdateStatusDto(string Status);
public record AssignDto(string AssignedToName);

[ApiController]
[Route("api/[controller]")]
public class ComplaintsController : ControllerBase
{
    private readonly FacilityDbContext _context;

    public ComplaintsController(FacilityDbContext context)
    {
        _context = context;
    }

    [HttpGet]
    public async Task<IActionResult> GetComplaints([FromQuery] string? buildingId)
    {
        var query = _context.Complaints.AsQueryable();
        if (!string.IsNullOrEmpty(buildingId))
        {
            query = query.Where(c => c.BuildingId == buildingId);
        }
        var complaints = await query.OrderByDescending(c => c.CreatedAt).ToListAsync();
        return Ok(complaints);
    }

    [HttpGet("{id}")]
    public async Task<IActionResult> GetComplaint(string id)
    {
        var complaint = await _context.Complaints.FindAsync(id);
        if (complaint == null) return NotFound();
        return Ok(complaint);
    }

    [HttpPost]
    public async Task<IActionResult> CreateComplaint([FromBody] Complaint complaint)
    {
        _context.Complaints.Add(complaint);
        await _context.SaveChangesAsync();
        return Ok(complaint);
    }

    [HttpPut("{id}/status")]
    public async Task<IActionResult> UpdateStatus(string id, [FromBody] UpdateStatusDto dto)
    {
        var complaint = await _context.Complaints.FindAsync(id);
        if (complaint == null) return NotFound();
        complaint.Status = dto.Status;
        if (dto.Status == "Resolved" || dto.Status == "Closed")
            complaint.ResolvedAt = DateTime.UtcNow;
        await _context.SaveChangesAsync();
        return Ok(complaint);
    }

    [HttpPut("{id}/assign")]
    public async Task<IActionResult> Assign(string id, [FromBody] AssignDto dto)
    {
        var complaint = await _context.Complaints.FindAsync(id);
        if (complaint == null) return NotFound();
        complaint.AssignedToName = dto.AssignedToName;
        complaint.Status = "In Progress";
        await _context.SaveChangesAsync();
        return Ok(complaint);
    }

    [AllowAnonymous]
    [HttpPost("seed")]
    public async Task<IActionResult> SeedComplaints()
    {
        if (await _context.Complaints.AnyAsync()) return Ok("Complaints already seeded");

        var room = await _context.Rooms.FirstOrDefaultAsync(r => r.Name == "Washroom A");
        
        var building = await _context.Buildings.FirstOrDefaultAsync();
        var buildingId = building?.Id ?? string.Empty;

        var c1 = new Complaint {
            Title = "Water Leakage",
            Description = "Pipe leaking near basin.",
            EntityId = room?.Id ?? "room-1",
            EntityType = "Room",
            EntityName = room?.Name ?? "Washroom A",
            BuildingId = buildingId,
            IsAutoGenerated = true,
            Priority = "Medium",
            Status = "Open",
            CreatedAt = DateTime.UtcNow.AddHours(-2)
        };

        var c2 = new Complaint {
            Title = "Light Failure",
            Description = "Main light flickering.",
            EntityId = "room-2",
            EntityType = "Room",
            EntityName = "Reception",
            BuildingId = buildingId,
            IsAutoGenerated = false,
            ReportedById = "user-123",
            Priority = "Low",
            Status = "Resolved",
            CreatedAt = DateTime.UtcNow.AddDays(-1)
        };

        _context.Complaints.AddRange(c1, c2);
        await _context.SaveChangesAsync();
        return Ok("Complaints seeded successfully");
    }
}
